### ISSUE TITLE
Missing address details - house number etc.

### ISSUE THREAD

**Issue by dekoza** [mwegrzynek/litex.regon#1]
When I make a request, the data is incomplete. Most of the data is there but the house number is missing.

**Comment by dekoza** [comment]
I found it in detailed info.

**Comment by mwegrzynek** [comment]
Unfortunately, that's how the information is structured in REGON database. I wrote about it to the IT guys at REGON: they are aware about the problem, but can not fix it because of the underlying db structure (they are aggregating data from multiple sources they don't have control on). Your solution is right -- fetch the detailed report.
